// <autogenerated />
#nullable enable
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.EntityFrameworkCore;
using VitalReach.Web.Data;

namespace VitalReach.Web.Components.Pages
{
    public partial class AdminUsers
    {
        [Inject] IDbContextFactory<CatalogDbContext> DbFactory { get; set; } = default!;
        [Inject] AuthenticationStateProvider AuthenticationStateProvider { get; set; } = default!;

        private List<AdminUser> Users = [];
        private AdminUser NewUser = new();
        private bool Adding, IsError;
        private string CurrentEmail = "";
        private string? Message;

        protected override async Task OnInitializedAsync()
        {
            var state = await AuthenticationStateProvider.GetAuthenticationStateAsync();
            CurrentEmail = state.User.FindFirst(System.Security.Claims.ClaimTypes.Email)?.Value ?? "Administrator";
            await Load();
        }

        private async Task Load()
        {
            await using var db = await DbFactory.CreateDbContextAsync();
            Users = await db.AdminUsers.AsNoTracking().OrderByDescending(x => x.IsActive).ThenBy(x => x.DisplayName).ToListAsync();
        }

        private void StartAdd()
        {
            NewUser = new AdminUser();
            Adding = true; Message = null;
        }

        private void CancelAdd()
        { Adding = false; Message = null; }

        private async Task AddUser()
        {
            await using var db = await DbFactory.CreateDbContextAsync();
            var email = NewUser.Email.Trim().ToLowerInvariant();
            if (await db.AdminUsers.AnyAsync(x => x.NormalizedEmail == email.ToUpper()))
            {
                Error("That email is already on the access list.");
                return;
            }

            var user = AdminUser.Create(email, NewUser.DisplayName, CurrentEmail);
            db.AdminUsers.Add(user); 
            await db.SaveChangesAsync();
            Adding = false; Success($"Granted access to {user.Email}."); 
            await Load();
        }

        private async Task Toggle(AdminUser selected)
        {
            await using var db = await DbFactory.CreateDbContextAsync();
            var user = await db.AdminUsers.FindAsync(selected.Id);
            if (user is null) return;
            if (user.IsActive && await db.AdminUsers.CountAsync(x => x.IsActive) <= 1)
            {
                Error("At least one active administrator is required.");
                return;
            }
            user.IsActive = !user.IsActive;
            user.UpdatedBy = CurrentEmail;
            user.UpdatedUtc = DateTimeOffset.UtcNow;
            await db.SaveChangesAsync(); Success($"{user.Email} is now {(user.IsActive ? "active" : "disabled")}.");
            await Load();
        }

        private async Task Delete(AdminUser selected)
        {
            await using var db = await DbFactory.CreateDbContextAsync();
            var user = await db.AdminUsers.FindAsync(selected.Id);
            if (user is null) return;
            if (user.IsActive && await db.AdminUsers.CountAsync(x => x.IsActive) <= 1)
            {
                Error("The last active administrator cannot be removed.");
                return;
            }
            db.AdminUsers.Remove(user);
            await db.SaveChangesAsync();
            Success($"Removed {user.Email}.");
            await Load();
        }

        private void Success(string message)
        {
            Message = message;
            IsError = false;
        }

        private void Error(string message)
        {
            Message = message;
            IsError = true;
        }

    }
}
