// <autogenerated />
#nullable enable
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.EntityFrameworkCore;
using VitalReach.Web.Data;

namespace VitalReach.Web.Components.Pages
{
    public partial class AdminProducts
    {

        [Inject] IDbContextFactory<CatalogDbContext> DbFactory { get; set; } = default!;
        [Inject] AuthenticationStateProvider AuthenticationStateProvider { get; set; } = default!;
        [Inject] ProductImageStorage ImageStorage { get; set; } = default!;

        private List<ProductEntity> Products = [];
        private ProductEntity? Editing;
        private string? Message;
        private bool IsError;
        private IBrowserFile? SelectedImage;
        private bool Saving;
        private string AdminEmail = "";
        protected override async Task OnInitializedAsync()
        {
            var state = await AuthenticationStateProvider.GetAuthenticationStateAsync();
            AdminEmail = state.User.FindFirst(System.Security.Claims.ClaimTypes.Email)?.Value ?? "Administrator";
            await Load();
        }

        private async Task Load()
        {
            await using var db = await DbFactory.CreateDbContextAsync();
            Products = await db.Products.AsNoTracking().OrderBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync();
        }

        private void NewProduct()
        {
            Editing = new ProductEntity
            {
                Theme = "teal-product",
                IsPublished = true,
                SortOrder = (Products.LastOrDefault()?.SortOrder ?? 0) + 10
            }; Message = null;
            IsError = false;
            SelectedImage = null;
        }

        private void Edit(ProductEntity product, bool clearMessage = true)
        {
            Editing = new ProductEntity
            {
                Id = product.Id,
                Slug = product.Slug,
                Name = product.Name,
                Price = product.Price,
                Category = product.Category,
                Benefit = product.Benefit,
                Description = product.Description,
                Detail = product.Detail,
                Theme = product.Theme,
                Orb = product.Orb,
                LabelOne = product.LabelOne,
                LabelTwo = product.LabelTwo,
                ImageUrl = product.ImageUrl,
                IsPublished = product.IsPublished,
                SortOrder = product.SortOrder,
                UpdatedUtc = product.UpdatedUtc
            };
            if (clearMessage)
            {
                Message = null;
                IsError = false;
            }
            SelectedImage = null;
        }

        private void SelectImage(InputFileChangeEventArgs args)
        {
            SelectedImage = args.File;
            Message = null;
        }

        private void RemoveImage()
        {
            if (Editing is null) return;
            Editing.ImageUrl = null;
            SelectedImage = null;
        }

        private async Task Save()
        {
            if (Editing is null) return;
            Saving = true;
            Editing.UpdatedUtc = DateTimeOffset.UtcNow;
            await using var db = await DbFactory.CreateDbContextAsync();
            var previousImageUrl = Editing.Id == 0
                ? null
                : await db.Products.AsNoTracking().Where(x => x.Id == Editing.Id).Select(x => x.ImageUrl).SingleOrDefaultAsync();
            string? uploadedImageUrl = null;
            try
            {
                if (SelectedImage is not null)
                {
                    uploadedImageUrl = await ImageStorage.SaveAsync(SelectedImage);
                    Editing.ImageUrl = uploadedImageUrl;
                }
                if (Editing.Id == 0) db.Products.Add(Editing); else db.Products.Update(Editing);
                await db.SaveChangesAsync();
                IsError = false;
                Message = $"Product “{Editing.Name}” has been saved successfully.";
                if (!string.Equals(previousImageUrl, Editing.ImageUrl, StringComparison.Ordinal))
                    await ImageStorage.DeleteAsync(previousImageUrl);
                SelectedImage = null;
                await Load(); var id = Editing.Id; Edit(Products.Single(x => x.Id == id), clearMessage: false);
            }
            catch (DbUpdateException)
            {
                await ImageStorage.DeleteAsync(uploadedImageUrl);
                Editing.ImageUrl = previousImageUrl;
                IsError = true;
                Message = "That slug is already in use. Choose a unique slug.";
            }
            catch (InvalidOperationException exception)
            {
                await ImageStorage.DeleteAsync(uploadedImageUrl);
                Editing.ImageUrl = previousImageUrl;
                IsError = true;
                Message = exception.Message;
            }
            catch (IOException)
            {
                await ImageStorage.DeleteAsync(uploadedImageUrl);
                Editing.ImageUrl = previousImageUrl;
                IsError = true;
                Message = "The image could not be stored. Please try again.";
            }
            finally { Saving = false; }
        }

        private async Task Delete()
        {
            if (Editing is null || Editing.Id == 0) return;
            await using var db = await DbFactory.CreateDbContextAsync();
            var product = await db.Products.FindAsync(Editing.Id);
            if (product is null) return;
            db.Products.Remove(product);
            await db.SaveChangesAsync();
            IsError = false;
            Message = $"Product “{product.Name}” has been deleted successfully.";
            await ImageStorage.DeleteAsync(product.ImageUrl);
            Editing = null;
            await Load();
        }


    }
}
