// <autogenerated />
#nullable enable
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using VitalReach.Web.Data;

namespace VitalReach.Web.Components.Pages
{
    public partial class AdminUsers
    {
        [Inject] IDbContextFactory<CatalogDbContext> DbFactory { get; set; } = default!;
        [Inject] AuthenticationStateProvider AuthenticationStateProvider { get; set; } = default!;
        [Inject] IAuthorizationService Authorization { get; set; } = default!;
        [Inject] private AdminConfirmation Confirmation { get; set; } = default!;

        private List<AdminUser> Users = [];
        private AdminUser NewUser = new();
        private bool Adding, IsError;
        private string CurrentEmail = "";
        private string? Message;

        protected override async Task OnInitializedAsync()
        {
            var state = await AuthenticationStateProvider.GetAuthenticationStateAsync();
            CurrentEmail = state.User.FindFirst(System.Security.Claims.ClaimTypes.Email)?.Value ?? "Administrator";
            await Load();
        }

        private async Task Load()
        {
            if (!await CanManage()) return;
            await using var db = await DbFactory.CreateDbContextAsync();
            Users = await db.AdminUsers.AsNoTracking().OrderByDescending(x => x.IsActive).ThenBy(x => x.DisplayName).ToListAsync();
        }

        private void StartAdd()
        {
            NewUser = new AdminUser();
            Adding = true; Message = null;
        }

        private void CancelAdd()
        { Adding = false; Message = null; }

        private Task AddUser() => Confirmation.RunAsync($"Grant administrator access to {NewUser.Email}? Clinical and superadmin permissions are granted separately.", AddUserCore);

        private async Task AddUserCore()
        {
            if (!await CanManage()) return;
            await using var db = await DbFactory.CreateDbContextAsync();
            var email = NewUser.Email.Trim().ToLowerInvariant();
            if (await db.AdminUsers.AnyAsync(x => x.NormalizedEmail == email.ToUpper()))
            {
                Error("That email is already on the access list.");
                return;
            }

            var user = AdminUser.Create(email, NewUser.DisplayName, CurrentEmail);
            db.AdminUsers.Add(user); 
            await db.SaveChangesAsync();
            Adding = false; Success($"Administrator “{user.Email}” has been added successfully.");
            await Load();
        }

        private Task Toggle(AdminUser selected) => Confirmation.RunAsync($"{(selected.IsActive ? "Disable" : "Enable")} administrator {selected.Email}? This affects their portal access and assigned permissions.", () => ToggleCore(selected));

        private async Task ToggleCore(AdminUser selected)
        {
            if (!await CanManage()) return;
            await using var db = await DbFactory.CreateDbContextAsync();
            var user = await db.AdminUsers.FindAsync(selected.Id);
            if (user is null) return;
            if (user.NormalizedEmail == CurrentEmail.ToUpperInvariant()) { Error("You cannot disable your own account."); return; }
            if (user.IsActive && user.IsSuperAdmin && await db.AdminUsers.CountAsync(x => x.IsActive && x.IsSuperAdmin) <= 1) { Error("At least one active superadmin is required."); return; }
            if (user.IsActive && await db.AdminUsers.CountAsync(x => x.IsActive) <= 1)
            {
                Error("At least one active administrator is required.");
                return;
            }
            user.IsActive = !selected.IsActive;
            user.UpdatedBy = CurrentEmail;
            user.UpdatedUtc = DateTimeOffset.UtcNow;
            await db.SaveChangesAsync(); Success($"Administrator “{user.Email}” has been {(user.IsActive ? "enabled" : "disabled")} successfully.");
            await Load();
        }

        private Task Delete(AdminUser selected) => Confirmation.RunAsync($"Remove administrator {selected.Email} and all their portal permissions? Access must be granted again to restore this account.", () => DeleteCore(selected));

        private async Task DeleteCore(AdminUser selected)
        {
            if (!await CanManage()) return;
            await using var db = await DbFactory.CreateDbContextAsync();
            var user = await db.AdminUsers.FindAsync(selected.Id);
            if (user is null) return;
            if (user.NormalizedEmail == CurrentEmail.ToUpperInvariant()) { Error("You cannot remove your own account."); return; }
            if (user.IsActive && user.IsSuperAdmin && await db.AdminUsers.CountAsync(x => x.IsActive && x.IsSuperAdmin) <= 1) { Error("The last active superadmin cannot be removed."); return; }
            if (user.IsActive && await db.AdminUsers.CountAsync(x => x.IsActive) <= 1)
            {
                Error("The last active administrator cannot be removed.");
                return;
            }
            db.AdminUsers.Remove(user);
            await db.SaveChangesAsync();
            Success($"Administrator “{user.Email}” has been removed successfully.");
            await Load();
        }

        private async Task<bool> CanManage()
        {
            var state = await AuthenticationStateProvider.GetAuthenticationStateAsync();
            if ((await Authorization.AuthorizeAsync(state.User, null, "SuperAdmin")).Succeeded) return true;
            Users = []; Adding = false; Error("Active superadmin access is required."); return false;
        }

        private Task ToggleRole(AdminUser selected, bool superadmin) => Confirmation.RunAsync(
            $"{((superadmin ? selected.IsSuperAdmin : selected.IsClinicalReviewer) ? "Revoke" : "Grant")} {(superadmin ? "superadmin" : "clinical reviewer")} access for {selected.Email}? " +
            (superadmin ? "Superadmins can manage other users and permissions." : "Clinical reviewers can access sensitive consultation records."), () => ToggleRoleCore(selected, superadmin));

        private async Task ToggleRoleCore(AdminUser selected, bool superadmin)
        {
            if (!await CanManage()) return;
            await using var db = await DbFactory.CreateDbContextAsync();
            var user = await db.AdminUsers.FindAsync(selected.Id);
            if (user is null) return;
            if (superadmin && user.NormalizedEmail == CurrentEmail.ToUpperInvariant()) { Error("You cannot revoke your own superadmin role."); return; }
            if (superadmin) user.IsSuperAdmin = !selected.IsSuperAdmin;
            else user.IsClinicalReviewer = !selected.IsClinicalReviewer;
            user.UpdatedBy = CurrentEmail; user.UpdatedUtc = DateTimeOffset.UtcNow;
            db.ConsultationAudits.Add(new ConsultationAudit { Reviewer = CurrentEmail, CreatedUtc = DateTime.UtcNow,
                Action = $"Access: {user.Email}; clinical={user.IsClinicalReviewer}; superadmin={user.IsSuperAdmin}" });
            await db.SaveChangesAsync();
            Success("Access updated. Clinical permissions are checked again on every record operation.");
            await Load();
        }

        private void Success(string message)
        {
            Message = message;
            IsError = false;
        }

        private void Error(string message)
        {
            Message = message;
            IsError = true;
        }

    }
}
