// <autogenerated />
#nullable enable
using Microsoft.AspNetCore.Components;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using VitalReach.Web.Data;

namespace VitalReach.Web.Components.Pages
{
    public partial class Home
    {
        [Inject] IDbContextFactory<CatalogDbContext> DbFactory { get; set; } = default!;
        private bool CartOpen, CheckoutOpen, MenuOpen;
        private readonly Dictionary<string, CartLine> Cart = [];
        private List<ProductEntity> Products = [];
        private HeadquartersSettings? Headquarters;
        private int CartCount => Cart.Values.Sum(x => x.Quantity);
        private decimal Subtotal => Cart.Values.Sum(x => x.Product.Price * x.Quantity);
        private string OrderContactUrl
        {
            get
            {
                var lines = string.Join("\n", Cart.Values.Select(x => $"{x.Quantity} × {x.Product.Name} — {Money(x.Product.Price * x.Quantity)}"));
                var body = Uri.EscapeDataString(
                    $"Hello VitalReach,\n\nI would like to order:\n{lines}\n\nSubtotal: {Money(Subtotal)}\n\nPlease confirm availability, shipping, and secure payment instructions.");
                return $"/contact?message={body}";
            }
        }
        private static string Money(decimal value) => value.ToString("C", CultureInfo.GetCultureInfo("en-US"));
        protected override async Task OnInitializedAsync()
        {
            await using var db = await DbFactory.CreateDbContextAsync();
            Products = await db.Products.AsNoTracking().Where(x => x.IsPublished).OrderBy(x => x.SortOrder).Take(3).ToListAsync();
            Headquarters = await db.Headquarters.AsNoTracking().SingleAsync(x => x.Id == 1);
        }
        private void AddToCart(ProductEntity product)
        {
            if (Cart.TryGetValue(product.Slug, out var line)) line.Quantity++; else Cart[product.Slug] = new(product, 1);
            CartOpen = true;
        }
        private void ChangeQuantity(string id, int amount)
        {
            Cart[id].Quantity += amount;
            if (Cart[id].Quantity < 1) Cart.Remove(id);
        }
        private void Remove(string id) => Cart.Remove(id);
        private void OpenCart() => CartOpen = true;
        private void CloseCart() => CartOpen = false;
        private void ToggleMenu() => MenuOpen = !MenuOpen;
        private void CloseMenu() => MenuOpen = false;
        private void BeginCheckout() { CartOpen = false; CheckoutOpen = true; }
        private void CloseCheckout() => CheckoutOpen = false;
        private sealed class CartLine(ProductEntity product, int quantity) { public ProductEntity Product { get; } = product; public int Quantity { get; set; } = quantity; }


    }
}
